version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    branches:
      only:
        - master
    steps:
      - add_ssh_keys:
          fingerprints:
            - "b8:68:4e:a1:94:4a:3a:58:7e:5a:37:00:e2:8a:d7:a4"
      - checkout
      - restore_cache:
          keys:
            - dependencies_circle_demo
      - run:
          name: Install
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: dependencies_circle_demo
      - run:
          name: Build
          command: yarn build
      - run:
          name: Prepare shell commands
          command: chmod +x deploy2.sh
      - run:
          name: Run Deploy to Github pages
          command: ./deploy2.sh
